---
- name: Get keycloak version
  shell: "{{ keycloak_home }}/current/bin/standalone.sh -v | tail -n 1 | awk '{print $2}'"
  register: keycloak_installed_version
  become: yes
  become_user: "{{ keycloak_user }}"
  changed_when: no
  # The file won't be there and/or the user won't exist if the installation hasn't run yet
  ignore_errors: yes
  check_mode: no
  tags: [keycloak, keycloak-install]

- name: Install keycloak
  # Use dynamic include so skipped tasks won't show in output
  include_tasks: install.yml
  when: keycloak_installed_version is undefined or
        keycloak_installed_version.stdout is undefined or
        keycloak_installed_version.stdout == ""
  tags: [keycloak, keycloak-install]

- name: Configure keycloak
  import_tasks: configure.yml
  tags: [keycloak, keycloak-configure]
