---
- hosts: jenkins_server
  gather_facts: true
  become: true
  become_user:
  vars:
    jenkins_hostname: 0.0.0.0
    jenkins_http_port: 8999
    jenkins_admin_username: admin
    jenkins_admin_password: admin
    jenkins_plugins:
      - git
      - ansible
      - localization-zh-cn
      - github-branch-source
      - workflow-job
      - sshd
      - ant
      - ws-cleanup
      - build-timeout
      - email-ext
      - pipeline-stage-view
      - ssh-slaves
      - timestamper
      - nodejs

  tasks:
    - name: Set repo_dir fact based on github_save_repo
      set_fact:
        repo_dir: "/srv/{{ github_save_repo.split('/')[-1] }}"
      when: github_save_repo is defined

    - name: Import java and jenkins roles
      include_role:
        name: "{{ item }}"
      loop:
        - java
        - jenkins
