---
dependencies: []

galaxy_info:
  role_name: go
  author: shaneholloman
  description: Go (language) installation for Linux.
  company: "shaneholloman"
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - go
    - golang

allow_duplicates: true
